# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "logstash" do |es|
    es.vm.box = "ubuntu/trusty64"
    es.vm.network :private_network, ip: "192.168.33.100"

    es.vm.provision "ansible" do |ansible| 
      ansible.playbook = "logstash.yml"
    end 
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "2048"]
  end

end
